import type { Activity } from "@/types"

// Dữ liệu mẫu cho hoạt động và thông báo
export const activities: Activity[] = [
  {
    id: "1",
    user: {
      id: "user1",
      name: "Nguyễn Văn A",
      initials: "NA",
    },
    action: 'đã thêm thẻ "Thiết kế logo" vào bảng "Dự án phát triển website"',
    time: "30 phút trước",
    boardId: "1",
    boardName: "Dự án phát triển website",
    read: false,
    type: "card",
    timestamp: Date.now() - 30 * 60 * 1000,
  },
  {
    id: "2",
    user: {
      id: "user2",
      name: "Trần Thị B",
      initials: "TB",
    },
    action: 'đã di chuyển thẻ "Viết nội dung" sang cột "Đang thực hiện"',
    time: "2 giờ trước",
    boardId: "1",
    boardName: "Dự án phát triển website",
    read: false,
    type: "card",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
  },
  {
    id: "3",
    user: {
      id: "user3",
      name: "Lê Văn C",
      initials: "LC",
    },
    action: 'đã thêm bình luận vào thẻ "Phân tích đối thủ"',
    time: "5 giờ trước",
    boardId: "1",
    boardName: "Dự án phát triển website",
    read: true,
    type: "comment",
    timestamp: Date.now() - 5 * 60 * 60 * 1000,
  },
  {
    id: "4",
    user: {
      id: "user4",
      name: "Phạm Thị D",
      initials: "PD",
    },
    action: 'đã thêm bạn vào bảng "Kế hoạch marketing Q2"',
    time: "1 ngày trước",
    boardId: "2",
    boardName: "Kế hoạch marketing Q2",
    read: true,
    type: "member",
    timestamp: Date.now() - 24 * 60 * 60 * 1000,
  },
  {
    id: "5",
    user: {
      id: "user5",
      name: "Hoàng Văn E",
      initials: "HE",
    },
    action: 'đã gán bạn vào thẻ "Thiết kế banner"',
    time: "2 ngày trước",
    boardId: "3",
    boardName: "Thiết kế UI/UX",
    read: true,
    type: "card",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: "6",
    user: {
      id: "user6",
      name: "Nguyễn Thị F",
      initials: "NF",
    },
    action: 'đã tạo bảng mới "Kế hoạch nội dung Q3"',
    time: "3 ngày trước",
    boardId: "4",
    boardName: "Kế hoạch nội dung Q3",
    read: true,
    type: "board",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: "7",
    user: {
      id: "user7",
      name: "Trần Văn G",
      initials: "TG",
    },
    action: 'đã chia sẻ bảng "Dự án phát triển website" với bạn',
    time: "4 ngày trước",
    boardId: "1",
    boardName: "Dự án phát triển website",
    read: true,
    type: "board",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: "8",
    user: {
      id: "user8",
      name: "Lê Thị H",
      initials: "LH",
    },
    action: 'đã thêm bình luận vào thẻ "Thiết kế logo"',
    time: "5 ngày trước",
    boardId: "1",
    boardName: "Dự án phát triển website",
    read: true,
    type: "comment",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
]
